import numpy as np
import math as mt
M,N = map(int,input().split())
print('Enter elements of first array: ')
ls1 = list(map(int,input().split()))
print('Enter elements of second array: ')
ls2= list(map(int, input().split()))
ar1 = np.array(ls1).reshape(M,N)
ar2 = np.array(ls2).reshape(M,N)
print(ar1)
print(ar2)
sub = np.subtract(ar1,ar2)
add= np.add(ar1,ar2)
multi = np.multiply(ar1,ar2)
power = np.power(ar1,ar2)
divi = np.floor_divide(ar1,ar2)
mod = np.mod(ar1,ar2)
print(add)
print(sub)
print(multi)
print(divi)
print(mod)
print(power)
